openapi: "3.0.3"
#this is based of https://www.traccar.org/api-reference/#tag/Commands/paths/~1commands~1%7Bid%7D/put
# you can view in  https://redocly.github.io/redoc/ #se modifico el HTML imprimir la documentacion
info:
  title: GCS (Ground  control Station MultiUAV)
  description: |-
    Descripcion de API de Alto nivel para comunicacion de Ros  con UAV.
    some usefull link:
    - [Repositorio](https://github.com/alvcaballero/multiuav_gui/tree/react)
  version: "2.3.5"
  contact:
    email: arpoma167@gmail.com
externalDocs:
  description: Find more about the project
  url: https://grvc.us.es/
servers:
  - url: https://localhost:4000/api/
tags:
  - name: Devices
    description: Management of UAV-devices
  - name: Positions
    description: Obtains raw data from the UAV
  - name: Missions
    description: Management the mission
  - name: Commands
    description: Send command the UAV
#  - name: Events
#    description: Obtiene informacion de eventos
#  - name: Notifications
#    description: Gestion de notificaciones de usuario
#  - name: session
#    description: for future
#  - name: Reports
#    description: for future
#  - name: Camera
#    description: for future

paths:
  /devices:
    get:
      tags:
        - Devices
      summary: Fetch a list of Devices
      description: Return the list of devices
      parameters:
        - $ref: "#/components/parameters/token"
      responses:
        200:
          description: (ok) list of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Device"
        400:
          description: No permission
          content: {}
    post:
      summary: Create a Device
      tags:
        - Devices
      parameters:
        - $ref: "#/components/parameters/token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BodyAddUAV"
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BodyAddUAV"
      x-codegen-request-body-name: body

  /devices/{id}:
    delete:
      summary: Delete a Device
      tags:
        - Devices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: No Content
          content: {}

  /postitions:
    get:
      summary: Fetches a list of Positions
      description: We strongly recommend using Websocket
        instead of periodically polling positions endpoint. Without any params, it
        returns a list of last known positions for all the user's Devices. _from_
        and _to_ fields are not required with _id_.
      tags:
        - Positions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Position"
  /loadmission/{id}:
    post:
      summary: Load mission to devices
      description: without any parameter,load the mission all UAV's
      tags:
        - Missions
      parameters:
        - name: id
          in: path
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoadMission"
        required: true
      responses:
        "204":
          description: No Content
          content: {}

  /commandmission/{id}:
    post:
      summary: Command to exec mission
      description: without any parameter,load the mission all UAV's
      tags:
        - Missions
      parameters:
        - name: id
          in: path
          schema:
            type: integer
      responses:
        "204":
          description: No Content
          content: {}

  /sendTask/:
    post:
      summary: Send a task to GCS for UAVs inspection
      description: without any parameter,load the mission all UAV's
      tags:
        - Missions
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/task_msg"
        required: true

      responses:
        "200":
          description: planned route
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/resulMissionTask"

  /comands/send:
    post:
      summary: Send command to devices
      description: Send command to  devices
      tags:
        - Commands
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Command"
        required: true
      responses:
        "200":
          description: Command sent
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Command"
        "400":
          description: Command no match
          content: {}
      x-codegen-request-body-name: body

components:
  #responses:

  parameters:
    token:
      name: token
      in: header
      description: Token de autenticacion
      required: false
      schema:
        type: string

  schemas:
    BodyAddUAV:
      type: object
      properties:
        uav_id:
          type: string
        uav_type:
          type: string

    Device:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
        lastUpdate:
          type: string
          description: in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
          format: date-time
        #model:
        #  type: string
        category:
          type: string
        #attributes:
        #  type: object
        #  properties: {}

    Position:
      type: object
      properties:
        #id:
        #  type: integer
        deviceId:
          type: integer
        #protocol:
        #  type: string
        deviceTime:
          type: string
          description: in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
          format: date-time
        #fixTime:
        #  type: string
        #  description: in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
        #  format: date-time
        #serverTime:
        #  type: string
        #  description: in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
        #  format: date-time
        #outdated:
        #  type: boolean
        #valid:
        #  type: boolean
        latitude:
          type: number
        longitude:
          type: number
        altitude:
          type: number
        speed:
          type: number
          description: in knots
        course:
          type: number
        #address:
        #  type: string
        #accuracy:
        #  type: number
        #network:
        #  type: object
        #  properties: {}
        attributes:
          type: object
          properties:
            protocol:
              type: string
            mission_state:
              type: string
            wp_reached:
              type: integer
            uav_state:
              type: string
            landed_state:
              type: string
            alarm:
              type: string
    LoadMission:
      type: object
      properties:
        description:
          type: string
          example: "mapeado de linea electrica"
        route:
          type: array
          items:
            $ref: "#/components/schemas/Route"
    Route:
      type: object
      properties:
        name:
          type: string
          example: "linea mata las cañas"
        uav:
          type: string
          example: "uav_1"
        wp:
          type: array
          items:
            $ref: "#/components/schemas/mission_waypoint"
        attributes:
          type: object
          properties:
            mode_landing:
              type: integer
              example: 2
            mode_yaw:
              type: integer
              example: 3
            mode_gimba:
              type: integer
              example: 0
            mode_trace:
              type: integer
              example: 0

    mission_waypoint:
      type: object
      properties:
        pos:
          type: array
          items:
            type: number
          example: [37.53395183, -6.30202933, 10]
          description: "latitude, longitude, relative altitude at takeoff"
          enum:
            - latitude
            - longitude
            - altitud
          minItems: 3
          maxItems: 3
        yaw:
          type: number
          example: 20
        gimbal:
          type: number
          example: 45
    task_msg:
      type: object
      properties:
        misision_id:
          type: integer
          example: 1234
          description: "identificador por GridWacth"
        objectivo:
          type: integer
          example: 0
          description: "Localizacion de incidencia 1: Inpecion de zona de aves, 2: Levantamiento Lidar"
        loc:
          type: object
          properties:
            tramo0:
              type: array
              items:
                type: object
                properties:
                  lat:
                    type: number
                    example: 37.0199008980604
                  lon:
                    type: number
                    example: -6.559872232408047
              example:
                - { lat: 37.121203, lon: -6.492668 }
                - { lat: 37.116616, lon: -6.484771 }
                - { lat: 37.107177, lon: -6.479203 }
            tramo1:
              type: array
              items:
                type: object
                properties:
                  lat:
                    type: number
                    example: 37.0199008980604
                  lon:
                    type: number
                    example: -6.559872232408047
              example:
                - { lat: 37.121100, lon: -6.495395 }
                - { lat: 37.119171, lon: -6.496007 }
        meteo:
          type: array
          items:
            type: object
            properties:
              lat:
                type: number
                example: 37.01455061559604
              lon:
                type: number
                example: -6.5625427378086489
              wind_vel:
                type: number
                example: 12
                description: "velocidad en metros/s"
              temp:
                type: number
                example: 38
                description: "temperatura en grados celcius"
              humidity:
                type: number
                example: 90
                description: "porcentaje "
              pressure:
                type: number
                example: 1201
                description: "presion atmosferica  en hPa"
          example:
            - lat: 37.01455061559604
              lon: -6.5625427378086489
              wind_vel: 12
              wind_dir: 360
              temp: 38
              humidity: 90
              pres_atm: 5
            - lat: 37.01455061559604
              lon: -6.5625427378086489
              wind_vel: 12
              wind_dir: 360
              temp: 38
              humidity: 90
              pres_atm: 5

    Command:
      type: object
      properties:
        deviceId:
          type: integer
        attributes:
          type: object
          properties: {}

    Notification:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        attributes:
          type: object
          properties: {}

    resulMissionTask:
      type: object
      properties:
        response:
          type: object
          properties:
            uav:
              type: string
              description: device identifier
            points:
              type: array
              description: List de points with "latitude, longitude, relative altitude at takeoff"
              items:
                type: array
                items:
                  type: number
                example: [37.53395183, -6.30202933, 10]
                description: "latitude, longitude, relative altitude at takeoff"
                enum:
                  - latitude
                  - longitude
                  - altitud
                minItems: 3
                maxItems: 3
        status:
          type: string
          description: status of planing
      example:
        response:
          uav: "uav_1"
          points:
            - [37.134092, -6.472401, 50]
            - [37.121203, -6.492668, 50]
            - [37.121203, -6.492668, 30]
            - [37.116616, -6.484771, 30]
            - [37.107177, -6.479203, 30]
            - [37.107177, -6.479203, 50]
            - [37.1211, -6.495395, 50]
            - [37.1211, -6.495395, 30]
            - [37.119171, -6.496007, 30]
            - [37.119171, -6.496007, 50]
            - [37.134092, -6.472401, 50]
        status: "OK"
